version: '3.8'
services:
  server:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        DB_PORT: ${POSTGRES_DB_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
      APP_PORT: ${APP_PORT}
      DB_PORT: ${POSTGRES_DB_PORT}  # Using DB port from environment
    ports:
      - "${SERVER_PORT}:${APP_PORT}"
    depends_on:
      - dev-db

  dev-db:
    image: postgres:13
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}