name: Deploy to VPS

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Run SSH Commands
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd ${{ secrets.REPO_PATH }}
          git pull origin main
          docker-compose --env-file ${{ secrets.ENV_FILE_PATH }} up --build -d
        EOF
